### ISSUE TITLE
lcdml restarts in jump to function

### ISSUE THREAD

**Issue by clear-sky** [Jomelo/LCDMenuLib2#33] opened 2018-11-18 15:21 UTC
when i try to jump to function lcdml restarts and shows lcdml version!
but after that goes to my function!

**Comment by Jomelo** [comment] 2018-11-18 18:10
Hello,
can you say me which controller you are using. At the normal Arduinos the examples are working correctly. 
I think there is anywhere in your code a bufferoverflow or a bad use case of a standard function.

**Comment by clear-sky** [comment] 2018-11-20 15:43
find the problem !
when i use  jump to function as a normal command it works well but when is use jump to function as exit condition this problem appears . example code:
if (LCDML.FUNC_close())     // ****** STABLE END *********
  {
    LCDML.OTHER_jumpToFunc(mFunc_myfunction);
   }

**Comment by Jomelo** [comment] 2018-11-20 21:19
Hello, 
i have reproduced the problem and have found a bug. 
Can you test the newest master version ? 
https://github.com/Jomelo/LCDMenuLib2/archive/master.zip

I haved found another bug: 
The screensaver would not start correctly when a menu function is active. This bug is also fixed.

**Comment by clear-sky** [comment] 2018-11-21 16:38
hi thanks for your notice
now this function does not work at all (when as exit condition) and exit function works normal i mean it seems i have not used this function

**Comment by clear-sky** [comment] 2018-11-28 19:19
hi jomelo!
have you any plan to active this function in this case?

**Comment by Jomelo** [comment] 2018-11-28 19:35
Hmm, 
i have tested it with my example function mFunc_information and on both function it is working:

Test  1:
```
 if(LCDML.FUNC_loop())           // ****** LOOP *********
  {    
    if(LCDML.BT_checkAny()) { // check if any button is pressed (enter, up, down, left, right)      
      //LCDML.FUNC_goBackToMenu();
      LCDML.OTHER_jumpToFunc(mFunc_p2);
    }
  }
```

Test 2:
```
if(LCDML.FUNC_close())      // ****** STABLE END *********
  {
    LCDML.OTHER_jumpToFunc(mFunc_p2);
    // you can here reset some global vars or do nothing
  }
```

I think i am testing the wrong position. How looks your function ?

**Comment by clear-sky** [comment] 2018-11-30 08:44
hi dear jomelo ! 
my function is similar yours:
if (LCDML.FUNC_close())     // ****** STABLE END *********
  {
    LCDML.OTHER_jumpToFunc(mFunc_Clock_Information);
  }

but i have 2 difference:
1- disabled screen saver(enabled it but no chance)
2- i am using lcd screen (ili9488 480x320) and have modified LCDMenuLib2.h as below:
#define _LCDML_DISP_cfg_max_rows             20  // max rows which are supported

**Comment by clear-sky** [comment] 2018-11-30 20:23
hi dear jomelo !
this is my code 
void mFunc_Set_Calendar(uint8_t param)
// *********************************************************************
{
  if (LCDML.FUNC_setup())         // ****** SETUP *********
  {
    tft.fillScreen(_LCDML_ADAFRUIT_BACKGROUND_COLOR);
    Wire.begin();
    Clock.getTime(year, month, date, DoW, hour, minute, second);
    Show_Set_Calendar_Menu();
    // starts a trigger event for the loop function every 100 milliseconds
    LCDML.FUNC_setLoopInterval(100);
  }

  if (LCDML.FUNC_loop())          // ****** LOOP *********
  {


    // - with LCDML_DISP_triggerMenu( milliseconds )
    // - with every button status change

    // check if any button is pressed (enter, up, down, left, right)
    if (LCDML.BT_checkAny())
    {
      if (LCDML.BT_checkRight())
      {
        LCDML.BT_resetRight();
        ++SET_MODE ;
        if (SET_MODE > 5)
        {
          SET_MODE = 1 ;
        }
      }
      if (LCDML.BT_checkLeft())
      {
        LCDML.BT_resetLeft();
        SET_MODE--  ;
        if (SET_MODE < 1)
        {
          SET_MODE = 5 ;
        }
      }
      if (LCDML.BT_checkUp())
      {
        LCDML.BT_resetUp();
        Increase_Calendar_Value();
      }
      if (LCDML.BT_checkDown())
      {
        LCDML.BT_resetDown();
        Decrease_Calendar_Value();
      }
      if (LCDML.BT_checkEnter())
      {
        LCDML.BT_resetEnter();
        //if (SET_MODE == 5) LCDML_DISP_funcend();
        if (SET_MODE == 1)
        {
          Save_Calendar_Value();
          LCDML.FUNC_goBackToMenu();
        }
      }
      Show_Set_Calendar_Menu();
    }
  }

  if (LCDML.FUNC_close())     // ****** STABLE END *********
  {
     LCDML.OTHER_jumpToFunc(mFunc_Clock_Information);
    // you can here reset some global vars or delete it
  }
}

**Comment by Jomelo** [comment] 2018-11-30 22:43
Thanks for your answer, i can no reproduce the problem, but i see at the moment not a differnt to other working functions. 
I am searching this problem now.

**Comment by Jomelo** [comment] 2018-12-02 09:11
Hello, 
i have create a develop branch.
There i have to change some more things to fix this problem

**Comment by Jomelo** [comment] 2018-12-02 11:39
Can you test the current develop version:
https://github.com/Jomelo/LCDMenuLib2/tree/develop

**Comment by clear-sky** [comment] 2018-12-02 15:07
hi dear jomelo! thanks for notice
now it works but incomplete(it moves cursor to target but can not open it)
regards

**Comment by clear-sky** [comment] 2019-01-09 16:44
hi dear jomelo and happy new year!
thanks for updates 
my program freezes  when i use jump to function as exit condition

**Comment by Jomelo** [comment] 2019-01-09 18:54
Hello, 
this is a bug in the current version. I try to fix the bug at the moment. (develop version) 
But at the moment i have long days on work and i have only a view hours on weekend to fix it. 
I do what i can do :-)

**Comment by Jomelo** [comment] 2019-01-13 19:03
I think it is now fixed in the current beta version 

Can you test this version: https://github.com/Jomelo/LCDMenuLib2/tree/develop

I have rewrite the complete library code because there were some bugs which i could not fix on the last code base.

One Line in the LCDML_display_menu tab have been changed.
old:
if ((tmp = LCDML.MENU_getObj()->getChild(LCDML.MENU_getScroll()))

new: 
if ((tmp = LCDML.MENU_getDisplayedObj()) != NULL)

**Comment by clear-sky** [comment] 2019-01-14 17:30
hi dear jomelo!
thanks! you are right !
the problem silved!!!

**Closed as completed** 2019-01-14 19:29 UTC
